import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormMessage } from "@/components/ui/form";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Check, Loader2 } from "lucide-react";

interface WaitlistFormProps {
  onSuccess?: (payload: {
    referralCode: string;
    referralCount: number;
    registrationOrder?: number | null;
    founderMember?: boolean | null;
    freeAccessUntil?: string | null;
  }) => void;
  defaultReferralCode?: string;
  translations?: {
    namePlaceholder: string;
    emailPlaceholder: string;
    referralPlaceholder: string;
    submitButton: string;
    submitting: string;
    successTitle: string;
    successMessage: string;
    founderMessage: string;
    regularMessage: string;
  };
}

export const WaitlistForm = ({ onSuccess, defaultReferralCode, translations }: WaitlistFormProps) => {
  const defaultTranslations = {
    namePlaceholder: "Tu nombre",
    emailPlaceholder: "tu@email.com",
    referralPlaceholder: "Código de referido (opcional)",
    submitButton: "Unirme a la lista",
    submitting: "Registrando...",
    successTitle: "¡Estás dentro!",
    successMessage: "Revisa tu email para los siguientes pasos",
    founderMessage: "Eres parte de los primeros 100 analistas fundadores. Tendrás 1 año gratis en todo lo que lancemos.",
    regularMessage: "Comparte tu enlace personal para desbloquear Oraculus y recompensas.",
  };

  const t = translations || defaultTranslations;
  const isEnglish = t.namePlaceholder.toLowerCase().includes("name") || t.namePlaceholder.toLowerCase().includes("your");

  const formSchema = z.object({
    name: z.string()
      .trim()
      .min(2, { message: isEnglish ? "Name must be at least 2 characters" : "El nombre debe tener al menos 2 caracteres" })
      .max(100, { message: isEnglish ? "Name cannot exceed 100 characters" : "El nombre no puede exceder 100 caracteres" }),
    email: z.string()
      .trim()
      .email({ message: isEnglish ? "Invalid email" : "Email inválido" })
      .max(255, { message: isEnglish ? "Email cannot exceed 255 characters" : "El email no puede exceder 255 caracteres" }),
    referralCode: z.string().trim().optional(),
  });

  type FormData = z.infer<typeof formSchema>;
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [successData, setSuccessData] = useState<{
    registrationOrder?: number | null;
    founderMember?: boolean | null;
  } | null>(null);

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      email: "",
      referralCode: defaultReferralCode || "",
    },
  });

  useEffect(() => {
    if (defaultReferralCode) {
      form.setValue("referralCode", defaultReferralCode);
    }
  }, [defaultReferralCode, form]);

  const onSubmit = async (data: FormData) => {
    setIsSubmitting(true);
    
    try {
      const { data: result, error } = await supabase
        .from("waitlist_users")
        .insert({
          name: data.name,
          email: data.email,
          referred_by: data.referralCode || null,
          referral_code: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) {
        if (error.code === "23505") {
          toast.error(isEnglish ? "This email is already registered" : "Este email ya está registrado");
        } else {
          toast.error(isEnglish ? "Error registering. Please try again." : "Error al registrarse. Inténtalo de nuevo.");
        }
        return;
      }

      setSuccess(true);
      setSuccessData({
        registrationOrder: result.registration_order,
        founderMember: result.founder_member,
      });
      toast.success(isEnglish ? "Registration successful! Check your email." : "¡Registro exitoso! Revisa tu email.");
      
      // Store email in localStorage for Oraculus access check
      localStorage.setItem("waitlist_email", data.email);
      
      if (result && onSuccess) {
        onSuccess({
          referralCode: result.referral_code,
          referralCount: result.referral_count,
          registrationOrder: result.registration_order,
          founderMember: result.founder_member,
          freeAccessUntil: result.free_access_until,
        });
      }
      
      form.reset();
    } catch (error) {
      toast.error(isEnglish ? "Unexpected error. Please try again." : "Error inesperado. Inténtalo de nuevo.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (success) {
    return (
      <div className="flex flex-col items-center gap-4 p-8 rounded-2xl border border-primary/20 bg-card/50 backdrop-blur-sm">
        <div className="w-16 h-16 rounded-full bg-primary/20 flex items-center justify-center">
          <Check className="w-8 h-8 text-primary" />
        </div>
        <div className="text-center">
          <h3 className="text-xl font-bold mb-2">{t.successTitle}</h3>
          <p className="text-muted-foreground">
            {t.successMessage}
          </p>
          {successData?.founderMember ? (
            <p className="text-sm text-primary font-semibold mt-2">
              {t.founderMessage}
            </p>
          ) : (
            <p className="text-sm text-muted-foreground mt-2">
              {t.regularMessage}
            </p>
          )}
        </div>
      </div>
    );
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 w-full max-w-md mx-auto">
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormControl>
                <Input
                  placeholder={t.namePlaceholder}
                  className="h-12 bg-card/50 border-border/50 focus:border-primary transition-colors"
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormControl>
                <Input
                  type="email"
                  placeholder={t.emailPlaceholder}
                  className="h-12 bg-card/50 border-border/50 focus:border-primary transition-colors"
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="referralCode"
          render={({ field }) => (
            <FormItem>
              <FormControl>
                <Input
                  placeholder={t.referralPlaceholder}
                  className="h-12 bg-card/50 border-border/50 focus:border-primary transition-colors"
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <Button
          type="submit"
          disabled={isSubmitting}
          className="w-full h-12 bg-gradient-primary hover:shadow-glow transition-all duration-300"
        >
          {isSubmitting ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              {t.submitting}
            </>
          ) : (
            t.submitButton
          )}
        </Button>
      </form>
    </Form>
  );
};