// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validar que las variables de entorno estén configuradas
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Error: Variables de entorno de Supabase no configuradas');
  console.error('VITE_SUPABASE_URL:', SUPABASE_URL ? '✅ Configurada' : '❌ Faltante');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅ Configurada' : '❌ Faltante');
  console.error('Por favor, configura estas variables en Vercel Dashboard → Settings → Environment Variables');
}

// Crear cliente con valores por defecto si faltan (para evitar errores)
const supabaseUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseKey = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'x-client-info': 'veridian-news@1.0.0',
    },
  },
});

// Exportar función para verificar si Supabase está configurado
export const isSupabaseConfigured = () => {
  return !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
           SUPABASE_URL !== 'https://placeholder.supabase.co' &&
           SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key');
};